# Generated by Django 5.0.3 on 2024-03-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scaling', models.CharField(max_length=1)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scalings', to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_attributes', to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='DefenseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_attributes', to='weapons.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='AttackAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_attributes', to='weapons.weapon')),
            ],
        ),
    ]
