# Generated by Django 4.2.11 on 2024-04-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='game',
            field=models.ForeignKey(default='Elden Ring', on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='games.game'),
            preserve_default=False,
        ),
    ]
