# Generated by Django 4.2.11 on 2024-04-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_weapon_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='game',
        ),
    ]
